// ==== Game State ====
const state = {
  runStartedAt: new Date().toISOString(),
  day: 1,
  citiesReached: 0,
  currentCity: null,
  routeHistory: [],
  cityTravelChoices: [],
  cityModifier: null,
  currentCarId: null,
  pendingRoadEvent: null,
  travelPendingDestination: null,
  runStatus: "active",
  money: CONFIG.startingMoney,
  totalSpent: 0,
  totalRevenue: 0,
  totalProfit: 0,
  dayCars: [],
  inventory: [],
  selectedCar: null,
  selectedInventoryId: null,
  pendingSale: null,
  buyerQueue: [],
  dayBuyerDemand: 1,
  buyersRemainingToday: 1,
  saleHistory: [],
  completedDeals: [],
  actions: [],
  saveSuggestedName: `junker-trader-log-${new Date().toISOString().replace(/[:.]/g, "-")}`,
  savePending: false,
  saveInFlight: false,
  opfsReady: false,
  opfsDir: null,
  runBlobUrl: null,
  actionsBlobUrl: null,
  persistenceMode: "none",
  logLines: [],
  runOver: false,
  dailyEvent: null,
  series: {
    money: [],
    spent: [],
    profit: [],
    balanceDelta: []
  }
};

// ==== DOM refs ====
const el = {
  topbar: document.getElementById("topbar"),
  buyerForecast: document.getElementById("buyer-forecast"),
  marketPanel: document.getElementById("market-panel"),
  marketCars: document.getElementById("market-cars"),
  runStatusPanel: document.getElementById("run-status-panel"),
  currentCarPanel: document.getElementById("current-car-panel"),
  travelPanel: document.getElementById("travel-panel"),
  travelChoices: document.getElementById("travel-choices"),
  eventPanel: document.getElementById("event-panel"),
  eventContent: document.getElementById("event-content"),
  eventActions: document.getElementById("event-actions"),
  negotiationPanel: document.getElementById("negotiation-panel"),
  negotiationContent: document.getElementById("negotiation-content"),
  garagePanel: document.getElementById("garage-panel"),
  inventoryList: document.getElementById("inventory-list"),
  garageContent: document.getElementById("garage-content"),
  repairActions: document.getElementById("repair-actions"),
  salePanel: document.getElementById("sale-panel"),
  saleContent: document.getElementById("sale-content"),
  counterofferPanel: document.getElementById("counteroffer-panel"),
  counterofferSlider: document.getElementById("counteroffer-slider"),
  counterofferSliderLabel: document.getElementById("counteroffer-slider-label"),
  counterofferBtn: document.getElementById("counteroffer-btn"),
  log: document.getElementById("event-log"),
  dealHistory: document.getElementById("deal-history"),
  runLogLink: document.getElementById("run-log-link"),
  actionsLogLink: document.getElementById("actions-log-link"),
  persistenceStatus: document.getElementById("persistence-status"),
  moneyGraph: document.getElementById("money-graph"),
  economyGraph: document.getElementById("economy-graph"),
  nextDayBtn: document.getElementById("next-day-btn"),
  toGarageFromMarketBtn: document.getElementById("to-garage-from-market-btn"),
  toTravelBtn: document.getElementById("to-travel-btn"),
  travelBackMarketBtn: document.getElementById("travel-back-market-btn"),
  toTravelFromGarageBtn: document.getElementById("to-travel-from-garage-btn"),
  toMarketFromGarageBtn: document.getElementById("to-market-from-garage-btn"),
  offerLowball: document.getElementById("offer-lowball"),
  offerFair: document.getElementById("offer-fair"),
  offerAsking: document.getElementById("offer-asking"),
  offerSlider: document.getElementById("offer-slider"),
  offerSliderLabel: document.getElementById("offer-slider-label"),
  offerCustom: document.getElementById("offer-custom"),
  walkAway: document.getElementById("walk-away"),
  inspectBtn: document.getElementById("inspect-btn"),
  sellSlider: document.getElementById("sell-slider"),
  sellSliderLabel: document.getElementById("sell-slider-label"),
  sellCustomBtn: document.getElementById("sell-custom-btn"),
  sellQuickBtn: document.getElementById("sell-quick-btn"),
  sellFairBtn: document.getElementById("sell-fair-btn"),
  sellPremiumBtn: document.getElementById("sell-premium-btn"),
  sellJunkyardBtn: document.getElementById("sell-junkyard-btn"),
  setCurrentCarBtn: document.getElementById("set-current-car-btn"),
  acceptSaleBtn: document.getElementById("accept-sale-btn"),
  rejectSaleBtn: document.getElementById("reject-sale-btn"),
  continueBtn: document.getElementById("continue-btn")
};
